# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 13:41
from __future__ import unicode_literals

from django.db import migrations



def loadfixture(apps, schema_editor):
    from django.core.management import call_command
    call_command('loaddata', 'users.json')

class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(loadfixture)
    ]
